# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:/usr/local/go/bin:$HOME/.cargo/bin:$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/arnow117/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="geoffgarside"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  z
  extract
)

source $ZSH/oh-my-zsh.sh

# User configuration
export LANG=en_US.UTF-8
export LC_ALL=C
# rust config
export CARGO_HTTP_MULTIPLEXING=false
export RUSTUP_DIST_SERVER="https://mirrors.ustc.edu.cn/rust-static"
export RUSTUP_UPDATE_ROOT="https://mirrors.ustc.edu.cn/rust-static/rustup"

# go config
export GOPATH=$HOME/go_dep:$HOME/workspace/rfuzzer/compiler/go
export GOROOT=/usr/local/go
export GOPROXY=https://mirrors.aliyun.com/goproxy/

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# where proxy
proxy () {
  export http_proxy="http://host.docker.internal:8001"
  export https_proxy="http://host.docker.internal:8001"
  echo "HTTP Proxy on"
}

# where noproxy
noproxy () {
  unset http_proxy
  unset https_proxy
  echo "HTTP Proxy off"
}

# Example aliases
alias ll="ls -la"

